packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild
  - msw
patchedDependencies:
  mupdf: patches/mupdf.patch
