/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardSettingsRouteRouteImport } from './routes/_dashboard/settings/route'
import { Route as DashboardContactsIndexRouteImport } from './routes/_dashboard/contacts/index'
import { Route as DashboardContactsIdRouteImport } from './routes/_dashboard/contacts/$id'
import { Route as DashboardP2pIndexRouteImport } from './routes/_dashboard/p2p/index'
import { Route as DashboardP2pLedgerTabsRouteImport } from './routes/_dashboard/p2p/ledger-tabs'
import { Route as DashboardP2pPendingRouteImport } from './routes/_dashboard/p2p/pending'
import { Route as DashboardP2pSharedLedgersRouteImport } from './routes/_dashboard/p2p/shared-ledgers'
import { Route as DashboardReconciliationIndexRouteImport } from './routes/_dashboard/reconciliation/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardSettingsAccountRouteImport } from './routes/_dashboard/settings/account'
import { Route as DashboardSettingsAppearanceRouteImport } from './routes/_dashboard/settings/appearance'
import { Route as DashboardSettingsBudgetsRouteImport } from './routes/_dashboard/settings/budgets'
import { Route as DashboardSettingsCategoriesRouteImport } from './routes/_dashboard/settings/categories'
import { Route as DashboardSettingsDisplayRouteImport } from './routes/_dashboard/settings/display'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/_dashboard/settings/notifications'
import { Route as DashboardSettingsProfileRouteImport } from './routes/_dashboard/settings/profile'
import { Route as DashboardSubscriptionsIndexRouteImport } from './routes/_dashboard/subscriptions/index'
import { Route as DashboardTransactionsIndexRouteImport } from './routes/_dashboard/transactions/index'
import { Route as DashboardWalletsIndexRouteImport } from './routes/_dashboard/wallets/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContactsIndexRoute = DashboardContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContactsIdRoute = DashboardContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardP2pIndexRoute = DashboardP2pIndexRouteImport.update({
  id: '/p2p/',
  path: '/p2p/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardP2pLedgerTabsRoute = DashboardP2pLedgerTabsRouteImport.update({
  id: '/p2p/ledger-tabs',
  path: '/p2p/ledger-tabs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardP2pPendingRoute = DashboardP2pPendingRouteImport.update({
  id: '/p2p/pending',
  path: '/p2p/pending',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardP2pSharedLedgersRoute =
  DashboardP2pSharedLedgersRouteImport.update({
    id: '/p2p/shared-ledgers',
    path: '/p2p/shared-ledgers',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReconciliationIndexRoute =
  DashboardReconciliationIndexRouteImport.update({
    id: '/reconciliation/',
    path: '/reconciliation/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsAppearanceRoute =
  DashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsBudgetsRoute =
  DashboardSettingsBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsCategoriesRoute =
  DashboardSettingsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsDisplayRoute =
  DashboardSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSubscriptionsIndexRoute =
  DashboardSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTransactionsIndexRoute =
  DashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardWalletsIndexRoute = DashboardWalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/contacts/$id': typeof DashboardContactsIdRoute
  '/p2p/ledger-tabs': typeof DashboardP2pLedgerTabsRoute
  '/p2p/pending': typeof DashboardP2pPendingRoute
  '/p2p/shared-ledgers': typeof DashboardP2pSharedLedgersRoute
  '/settings/account': typeof DashboardSettingsAccountRoute
  '/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/settings/budgets': typeof DashboardSettingsBudgetsRoute
  '/settings/categories': typeof DashboardSettingsCategoriesRoute
  '/settings/display': typeof DashboardSettingsDisplayRoute
  '/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/settings/profile': typeof DashboardSettingsProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/contacts/': typeof DashboardContactsIndexRoute
  '/p2p/': typeof DashboardP2pIndexRoute
  '/reconciliation/': typeof DashboardReconciliationIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/subscriptions/': typeof DashboardSubscriptionsIndexRoute
  '/transactions/': typeof DashboardTransactionsIndexRoute
  '/wallets/': typeof DashboardWalletsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/': typeof DashboardIndexRoute
  '/contacts/$id': typeof DashboardContactsIdRoute
  '/p2p/ledger-tabs': typeof DashboardP2pLedgerTabsRoute
  '/p2p/pending': typeof DashboardP2pPendingRoute
  '/p2p/shared-ledgers': typeof DashboardP2pSharedLedgersRoute
  '/settings/account': typeof DashboardSettingsAccountRoute
  '/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/settings/budgets': typeof DashboardSettingsBudgetsRoute
  '/settings/categories': typeof DashboardSettingsCategoriesRoute
  '/settings/display': typeof DashboardSettingsDisplayRoute
  '/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/settings/profile': typeof DashboardSettingsProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/contacts': typeof DashboardContactsIndexRoute
  '/p2p': typeof DashboardP2pIndexRoute
  '/reconciliation': typeof DashboardReconciliationIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/subscriptions': typeof DashboardSubscriptionsIndexRoute
  '/transactions': typeof DashboardTransactionsIndexRoute
  '/wallets': typeof DashboardWalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/contacts/$id': typeof DashboardContactsIdRoute
  '/_dashboard/p2p/ledger-tabs': typeof DashboardP2pLedgerTabsRoute
  '/_dashboard/p2p/pending': typeof DashboardP2pPendingRoute
  '/_dashboard/p2p/shared-ledgers': typeof DashboardP2pSharedLedgersRoute
  '/_dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/_dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/_dashboard/settings/budgets': typeof DashboardSettingsBudgetsRoute
  '/_dashboard/settings/categories': typeof DashboardSettingsCategoriesRoute
  '/_dashboard/settings/display': typeof DashboardSettingsDisplayRoute
  '/_dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/_dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/_dashboard/p2p/': typeof DashboardP2pIndexRoute
  '/_dashboard/reconciliation/': typeof DashboardReconciliationIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/subscriptions/': typeof DashboardSubscriptionsIndexRoute
  '/_dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/_dashboard/wallets/': typeof DashboardWalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/settings'
    | '/contacts/$id'
    | '/p2p/ledger-tabs'
    | '/p2p/pending'
    | '/p2p/shared-ledgers'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/budgets'
    | '/settings/categories'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/profile'
    | '/api/auth/$'
    | '/contacts/'
    | '/p2p/'
    | '/reconciliation/'
    | '/settings/'
    | '/subscriptions/'
    | '/transactions/'
    | '/wallets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/contacts/$id'
    | '/p2p/ledger-tabs'
    | '/p2p/pending'
    | '/p2p/shared-ledgers'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/budgets'
    | '/settings/categories'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/profile'
    | '/api/auth/$'
    | '/contacts'
    | '/p2p'
    | '/reconciliation'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/wallets'
  id:
    | '__root__'
    | '/_dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/_dashboard/settings'
    | '/_dashboard/'
    | '/_dashboard/contacts/$id'
    | '/_dashboard/p2p/ledger-tabs'
    | '/_dashboard/p2p/pending'
    | '/_dashboard/p2p/shared-ledgers'
    | '/_dashboard/settings/account'
    | '/_dashboard/settings/appearance'
    | '/_dashboard/settings/budgets'
    | '/_dashboard/settings/categories'
    | '/_dashboard/settings/display'
    | '/_dashboard/settings/notifications'
    | '/_dashboard/settings/profile'
    | '/api/auth/$'
    | '/_dashboard/contacts/'
    | '/_dashboard/p2p/'
    | '/_dashboard/reconciliation/'
    | '/_dashboard/settings/'
    | '/_dashboard/subscriptions/'
    | '/_dashboard/transactions/'
    | '/_dashboard/wallets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/contacts/': {
      id: '/_dashboard/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof DashboardContactsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/contacts/$id': {
      id: '/_dashboard/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof DashboardContactsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/p2p/': {
      id: '/_dashboard/p2p/'
      path: '/p2p'
      fullPath: '/p2p/'
      preLoaderRoute: typeof DashboardP2pIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/p2p/ledger-tabs': {
      id: '/_dashboard/p2p/ledger-tabs'
      path: '/p2p/ledger-tabs'
      fullPath: '/p2p/ledger-tabs'
      preLoaderRoute: typeof DashboardP2pLedgerTabsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/p2p/pending': {
      id: '/_dashboard/p2p/pending'
      path: '/p2p/pending'
      fullPath: '/p2p/pending'
      preLoaderRoute: typeof DashboardP2pPendingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/p2p/shared-ledgers': {
      id: '/_dashboard/p2p/shared-ledgers'
      path: '/p2p/shared-ledgers'
      fullPath: '/p2p/shared-ledgers'
      preLoaderRoute: typeof DashboardP2pSharedLedgersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/reconciliation/': {
      id: '/_dashboard/reconciliation/'
      path: '/reconciliation'
      fullPath: '/reconciliation/'
      preLoaderRoute: typeof DashboardReconciliationIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/account': {
      id: '/_dashboard/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/appearance': {
      id: '/_dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/budgets': {
      id: '/_dashboard/settings/budgets'
      path: '/budgets'
      fullPath: '/settings/budgets'
      preLoaderRoute: typeof DashboardSettingsBudgetsRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/categories': {
      id: '/_dashboard/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof DashboardSettingsCategoriesRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/display': {
      id: '/_dashboard/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof DashboardSettingsDisplayRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/notifications': {
      id: '/_dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/settings/profile': {
      id: '/_dashboard/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/_dashboard/subscriptions/': {
      id: '/_dashboard/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof DashboardSubscriptionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/transactions/': {
      id: '/_dashboard/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof DashboardTransactionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/wallets/': {
      id: '/_dashboard/wallets/'
      path: '/wallets'
      fullPath: '/wallets/'
      preLoaderRoute: typeof DashboardWalletsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute
  DashboardSettingsAppearanceRoute: typeof DashboardSettingsAppearanceRoute
  DashboardSettingsBudgetsRoute: typeof DashboardSettingsBudgetsRoute
  DashboardSettingsCategoriesRoute: typeof DashboardSettingsCategoriesRoute
  DashboardSettingsDisplayRoute: typeof DashboardSettingsDisplayRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
    DashboardSettingsAppearanceRoute: DashboardSettingsAppearanceRoute,
    DashboardSettingsBudgetsRoute: DashboardSettingsBudgetsRoute,
    DashboardSettingsCategoriesRoute: DashboardSettingsCategoriesRoute,
    DashboardSettingsDisplayRoute: DashboardSettingsDisplayRoute,
    DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
    DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardContactsIdRoute: typeof DashboardContactsIdRoute
  DashboardP2pLedgerTabsRoute: typeof DashboardP2pLedgerTabsRoute
  DashboardP2pPendingRoute: typeof DashboardP2pPendingRoute
  DashboardP2pSharedLedgersRoute: typeof DashboardP2pSharedLedgersRoute
  DashboardContactsIndexRoute: typeof DashboardContactsIndexRoute
  DashboardP2pIndexRoute: typeof DashboardP2pIndexRoute
  DashboardReconciliationIndexRoute: typeof DashboardReconciliationIndexRoute
  DashboardSubscriptionsIndexRoute: typeof DashboardSubscriptionsIndexRoute
  DashboardTransactionsIndexRoute: typeof DashboardTransactionsIndexRoute
  DashboardWalletsIndexRoute: typeof DashboardWalletsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardContactsIdRoute: DashboardContactsIdRoute,
  DashboardP2pLedgerTabsRoute: DashboardP2pLedgerTabsRoute,
  DashboardP2pPendingRoute: DashboardP2pPendingRoute,
  DashboardP2pSharedLedgersRoute: DashboardP2pSharedLedgersRoute,
  DashboardContactsIndexRoute: DashboardContactsIndexRoute,
  DashboardP2pIndexRoute: DashboardP2pIndexRoute,
  DashboardReconciliationIndexRoute: DashboardReconciliationIndexRoute,
  DashboardSubscriptionsIndexRoute: DashboardSubscriptionsIndexRoute,
  DashboardTransactionsIndexRoute: DashboardTransactionsIndexRoute,
  DashboardWalletsIndexRoute: DashboardWalletsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
