//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "bank_statement_rows"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(export, rename = "BankStatementRow")]
pub struct Model {
    pub id: String,
    pub date: DateTimeWithTimeZone,
    pub description: String,
    #[ts(type = "string | null")]
    pub debit: Option<Decimal>,
    #[ts(type = "string | null")]
    pub credit: Option<Decimal>,
    #[ts(type = "string")]
    pub balance: Decimal,
    pub user_id: String,
    pub is_matched: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Date,
    Description,
    Debit,
    Credit,
    Balance,
    UserId,
    IsMatched,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    StatementTxnMatches,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::String(StringLen::None).def().null(),
            Self::Date => ColumnType::TimestampWithTimeZone.def(),
            Self::Description | Self::UserId => ColumnType::String(StringLen::None).def(),
            Self::Debit | Self::Credit => ColumnType::Decimal(None).def().null(),
            Self::Balance => ColumnType::Decimal(None).def(),
            Self::IsMatched => ColumnType::Boolean.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::StatementTxnMatches => {
                Entity::has_many(super::statement_txn_matches::Entity).into()
            }
        }
    }
}

impl Related<super::statement_txn_matches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatementTxnMatches.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        super::statement_txn_matches::Relation::Transactions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::statement_txn_matches::Relation::BankStatementRows
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
