//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::IdentifierType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "contact_identifiers"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(export, rename = "ContactIdentifier")]
pub struct Model {
    pub id: String,
    pub contact_id: String,
    pub r#type: IdentifierType,
    pub value: String,
    pub linked_user_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ContactId,
    Type,
    Value,
    LinkedUserId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Contacts,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id | Self::LinkedUserId => ColumnType::String(StringLen::None).def().null(),
            Self::ContactId | Self::Type | Self::Value => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Contacts => Entity::belongs_to(super::contacts::Entity)
                .from(Column::ContactId)
                .to(super::contacts::Column::Id)
                .into(),
        }
    }
}

impl Related<super::contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contacts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
