//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "contact_staging"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(export, rename = "ContactStaging")]
pub struct Model {
    pub id: String,
    pub user_id: String,
    pub ocr_job_id: String,
    pub name: String,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub upi_id: Option<String>,
    pub status: String,
    #[ts(as = "Option<crate::ExportedJsonValue>")]
    pub candidates: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    UserId,
    OcrJobId,
    Name,
    Phone,
    Email,
    UpiId,
    Status,
    Candidates,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id | Self::UserId | Self::OcrJobId | Self::Name | Self::Status => {
                ColumnType::String(StringLen::None).def()
            }
            Self::Phone | Self::Email | Self::UpiId => {
                ColumnType::String(StringLen::None).def().null()
            }
            Self::Candidates => ColumnType::Json.def().null(),
            Self::CreatedAt | Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
