//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "contacts"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "Contact",
    export_to = "../../../packages/types/src/db/Contact.ts"
)]
pub struct Model {
    pub id: String,
    pub name: String,
    pub phone: Option<String>,
    pub is_pinned: bool,
    pub normalized_name: Option<String>,
    pub phonetic_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Phone,
    IsPinned,
    NormalizedName,
    PhoneticName,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ContactIdentifiers,
    ContactLinks,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::String(StringLen::None).def().null(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Phone => ColumnType::String(StringLen::None).def().null(),
            Self::IsPinned => ColumnType::Boolean.def(),
            Self::NormalizedName => ColumnType::String(StringLen::None).def().null(),
            Self::PhoneticName => ColumnType::String(StringLen::None).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ContactIdentifiers => Entity::has_many(super::contact_identifiers::Entity).into(),
            Self::ContactLinks => Entity::has_many(super::contact_links::Entity).into(),
        }
    }
}

impl Related<super::contact_identifiers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactIdentifiers.def()
    }
}

impl Related<super::contact_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactLinks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::contact_links::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::contact_links::Relation::Contacts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
