//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::{LedgerTabStatus, LedgerTabType};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "ledger_tabs"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "LedgerTab",
    export_to = "../../../packages/types/src/db/LedgerTab.ts"
)]
pub struct Model {
    pub id: String,
    pub creator_id: String,
    pub counterparty_id: Option<String>,
    pub tab_type: LedgerTabType,
    pub title: String,
    #[ts(type = "string")]
    pub target_amount: Decimal,
    pub status: LedgerTabStatus,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreatorId,
    CounterpartyId,
    TabType,
    Title,
    TargetAmount,
    Status,
    CreatedAt,
    UpdatedAt,
    Description,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id | Self::CounterpartyId | Self::Description => {
                ColumnType::String(StringLen::None).def().null()
            }
            Self::CreatorId | Self::TabType | Self::Title | Self::Status => {
                ColumnType::String(StringLen::None).def()
            }
            Self::TargetAmount => ColumnType::Decimal(None).def(),
            Self::CreatedAt | Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::CreatorId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
