//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "ocr_jobs"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "OcrJob",
    export_to = "../../../packages/types/src/db/OcrJob.ts"
)]
pub struct Model {
    pub id: String,
    pub user_id: String,
    pub status: String,
    pub r2_key: String,
    #[ts(as = "Option<crate::ExportedJsonValue>")]
    pub processed_data: Option<Json>,
    pub error: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub p_hash: Option<String>,
    pub auto_confirm: bool,
    pub wallet_id: Option<String>,
    pub category_id: Option<String>,
    pub transaction_id: Option<String>,
    pub started_at: Option<DateTime>,
    pub retry_count: i32,
    pub last_error: Option<String>,
    pub scheduled_at: Option<DateTime>,
    pub raw_key: Option<String>,
    pub is_high_res: bool,
    pub schema_version: i32,
    #[ts(as = "Option<crate::ExportedJsonValue>")]
    pub resolution_candidates: Option<Json>,
    pub trace_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    UserId,
    Status,
    R2Key,
    ProcessedData,
    Error,
    CreatedAt,
    UpdatedAt,
    PHash,
    AutoConfirm,
    WalletId,
    CategoryId,
    TransactionId,
    StartedAt,
    RetryCount,
    LastError,
    ScheduledAt,
    RawKey,
    IsHighRes,
    SchemaVersion,
    ResolutionCandidates,
    TraceId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id | Self::UserId | Self::Status | Self::R2Key => {
                ColumnType::String(StringLen::None).def()
            }
            Self::ProcessedData | Self::ResolutionCandidates => ColumnType::Json.def().null(),
            Self::Error
            | Self::PHash
            | Self::WalletId
            | Self::CategoryId
            | Self::TransactionId
            | Self::LastError
            | Self::RawKey
            | Self::TraceId => ColumnType::String(StringLen::None).def().null(),
            Self::CreatedAt | Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::AutoConfirm | Self::IsHighRes => ColumnType::Boolean.def(),
            Self::StartedAt | Self::ScheduledAt => ColumnType::DateTime.def().null(),
            Self::RetryCount | Self::SchemaVersion => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
