//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::P2pRequestStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "p2p_requests"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "P2pRequest",
    export_to = "../../../packages/types/src/db/P2pRequest.ts"
)]
pub struct Model {
    pub id: String,
    pub sender_user_id: String,
    pub receiver_email: String,
    #[ts(as = "crate::ExportedJsonValue")]
    pub transaction_data: Json,
    pub status: P2pRequestStatus,
    pub linked_txn_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SenderUserId,
    ReceiverEmail,
    TransactionData,
    Status,
    LinkedTxnId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id | Self::LinkedTxnId => ColumnType::String(StringLen::None).def().null(),
            Self::SenderUserId | Self::ReceiverEmail => ColumnType::String(StringLen::None).def(),
            Self::TransactionData => ColumnType::Json.def(),
            Self::Status => ColumnType::String(StringLen::N(20)).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::SenderUserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
