//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::TransactionDirection;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "p2p_transfers"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(export, rename = "P2pTransfer")]
pub struct Model {
    pub id: String,
    pub transaction_id: String,
    pub direction: TransactionDirection,
    pub counterparty_name: String,
    pub counterparty_phone: Option<String>,
    pub counterparty_upi_id: Option<String>,
    pub is_merchant: bool,
    pub upi_transaction_id: Option<String>,
    pub google_transaction_id: Option<String>,
    pub source_bank_account: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    TransactionId,
    Direction,
    CounterpartyName,
    CounterpartyPhone,
    CounterpartyUpiId,
    IsMerchant,
    UpiTransactionId,
    GoogleTransactionId,
    SourceBankAccount,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Transactions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id
            | Self::CounterpartyPhone
            | Self::CounterpartyUpiId
            | Self::UpiTransactionId
            | Self::GoogleTransactionId
            | Self::SourceBankAccount => ColumnType::String(StringLen::None).def().null(),
            Self::TransactionId | Self::Direction | Self::CounterpartyName => {
                ColumnType::String(StringLen::None).def()
            }
            Self::IsMerchant => ColumnType::Boolean.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Transactions => Entity::belongs_to(super::transactions::Entity)
                .from(Column::TransactionId)
                .to(super::transactions::Column::Id)
                .into(),
        }
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
