//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "statement_txn_matches"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "StatementTxnMatch",
    export_to = "../../../packages/types/src/db/StatementTxnMatch.ts"
)]
pub struct Model {
    pub row_id: String,
    pub transaction_id: String,
    #[ts(type = "string")]
    pub confidence: Decimal,
    pub matched_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    RowId,
    TransactionId,
    Confidence,
    MatchedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    RowId,
    TransactionId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    BankStatementRows,
    Transactions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::RowId | Self::TransactionId => ColumnType::String(StringLen::None).def(),
            Self::Confidence => ColumnType::Decimal(None).def(),
            Self::MatchedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::BankStatementRows => Entity::belongs_to(super::bank_statement_rows::Entity)
                .from(Column::RowId)
                .to(super::bank_statement_rows::Column::Id)
                .into(),
            Self::Transactions => Entity::belongs_to(super::transactions::Entity)
                .from(Column::TransactionId)
                .to(super::transactions::Column::Id)
                .into(),
        }
    }
}

impl Related<super::bank_statement_rows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BankStatementRows.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
