//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::AlertChannel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "sub_alerts"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "SubAlert",
    export_to = "../../../packages/types/src/db/SubAlert.ts"
)]
pub struct Model {
    pub id: String,
    pub subscription_id: String,
    pub days_before: i32,
    pub sent_at: Option<DateTimeWithTimeZone>,
    pub channel: AlertChannel,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SubscriptionId,
    DaysBefore,
    SentAt,
    Channel,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Subscriptions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::String(StringLen::None).def().null(),
            Self::SubscriptionId | Self::Channel => ColumnType::String(StringLen::None).def(),
            Self::DaysBefore => ColumnType::Integer.def(),
            Self::SentAt => ColumnType::TimestampWithTimeZone.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Subscriptions => Entity::belongs_to(super::subscriptions::Entity)
                .from(Column::SubscriptionId)
                .to(super::subscriptions::Column::Id)
                .into(),
        }
    }
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
