//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::SubscriptionCycle;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "subscriptions"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "Subscription",
    export_to = "../../../packages/types/src/db/Subscription.ts"
)]
pub struct Model {
    pub id: String,
    pub user_id: String,
    pub name: String,
    #[ts(type = "string")]
    pub amount: Decimal,
    pub cycle: SubscriptionCycle,
    pub start_date: DateTimeWithTimeZone,
    pub next_charge_date: DateTimeWithTimeZone,
    #[ts(as = "Option<crate::ExportedJsonValue>")]
    pub detection_keywords: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    UserId,
    Name,
    Amount,
    Cycle,
    StartDate,
    NextChargeDate,
    DetectionKeywords,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    SubAlerts,
    SubscriptionCharges,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::String(StringLen::None).def().null(),
            Self::UserId | Self::Name | Self::Cycle => ColumnType::String(StringLen::None).def(),
            Self::Amount => ColumnType::Decimal(None).def(),
            Self::StartDate | Self::NextChargeDate => ColumnType::TimestampWithTimeZone.def(),
            Self::DetectionKeywords => ColumnType::Json.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::SubAlerts => Entity::has_many(super::sub_alerts::Entity).into(),
            Self::SubscriptionCharges => {
                Entity::has_many(super::subscription_charges::Entity).into()
            }
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::sub_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubAlerts.def()
    }
}

impl Related<super::subscription_charges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionCharges.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
