//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "subscription_charges"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "SubscriptionCharge",
    export_to = "../../../packages/types/src/db/SubscriptionCharge.ts"
)]
pub struct Model {
    pub id: String,
    pub subscription_id: String,
    pub transaction_id: Option<String>,
    pub charged_on: DateTimeWithTimeZone,
    #[ts(type = "string")]
    pub amount: Decimal,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SubscriptionId,
    TransactionId,
    ChargedOn,
    Amount,
    Status,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Subscriptions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id | Self::TransactionId => ColumnType::String(StringLen::None).def().null(),
            Self::SubscriptionId | Self::Status => ColumnType::String(StringLen::None).def(),
            Self::ChargedOn => ColumnType::TimestampWithTimeZone.def(),
            Self::Amount => ColumnType::Decimal(None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Subscriptions => Entity::belongs_to(super::subscriptions::Entity)
                .from(Column::SubscriptionId)
                .to(super::subscriptions::Column::Id)
                .into(),
        }
    }
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
