//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::{TransactionDirection, TransactionSource, TransactionStatus};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "transactions"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "Transaction",
    export_to = "../../../packages/types/src/db/Transaction.ts"
)]
pub struct Model {
    pub id: String,
    pub user_id: String,
    #[ts(type = "string")]
    pub amount: Decimal,
    pub direction: TransactionDirection,
    pub date: DateTimeWithTimeZone,
    pub source: TransactionSource,
    pub status: TransactionStatus,
    pub purpose_tag: Option<String>,
    pub group_id: Option<String>,
    pub source_wallet_id: Option<String>,
    pub destination_wallet_id: Option<String>,
    pub ledger_tab_id: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub notes: Option<String>,
    pub category_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    UserId,
    Amount,
    Direction,
    Date,
    Source,
    Status,
    PurposeTag,
    GroupId,
    SourceWalletId,
    DestinationWalletId,
    LedgerTabId,
    DeletedAt,
    Notes,
    CategoryId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    P2pTransfers,
    Purchases,
    StatementTxnMatches,
    TransactionEdits,
    TransactionMetadata,
    TransactionSources,
    TxnParties,
    Users,
    Categories,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id
            | Self::PurposeTag
            | Self::GroupId
            | Self::SourceWalletId
            | Self::DestinationWalletId
            | Self::LedgerTabId
            | Self::Notes
            | Self::CategoryId => ColumnType::String(StringLen::None).def().null(),
            Self::UserId => ColumnType::String(StringLen::None).def(),
            Self::Amount => ColumnType::Decimal(None).def(),
            Self::Direction | Self::Source | Self::Status => {
                ColumnType::String(StringLen::N(20)).def()
            }
            Self::Date => ColumnType::TimestampWithTimeZone.def(),
            Self::DeletedAt => ColumnType::TimestampWithTimeZone.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::P2pTransfers => Entity::has_many(super::p2p_transfers::Entity).into(),
            Self::Purchases => Entity::has_many(super::purchases::Entity).into(),
            Self::StatementTxnMatches => {
                Entity::has_many(super::statement_txn_matches::Entity).into()
            }
            Self::TransactionEdits => Entity::has_many(super::transaction_edits::Entity).into(),
            Self::TransactionMetadata => {
                Entity::has_one(super::transaction_metadata::Entity).into()
            }
            Self::TransactionSources => Entity::has_many(super::transaction_sources::Entity).into(),
            Self::TxnParties => Entity::has_many(super::txn_parties::Entity).into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
            Self::Categories => Entity::belongs_to(super::categories::Entity)
                .from(Column::CategoryId)
                .to(super::categories::Column::Id)
                .into(),
        }
    }
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::p2p_transfers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::P2pTransfers.def()
    }
}

impl Related<super::purchases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Purchases.def()
    }
}

impl Related<super::statement_txn_matches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatementTxnMatches.def()
    }
}

impl Related<super::transaction_edits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionEdits.def()
    }
}

impl Related<super::transaction_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionMetadata.def()
    }
}

impl Related<super::transaction_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionSources.def()
    }
}

impl Related<super::txn_parties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TxnParties.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::bank_statement_rows::Entity> for Entity {
    fn to() -> RelationDef {
        super::statement_txn_matches::Relation::BankStatementRows.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::statement_txn_matches::Relation::Transactions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
