//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::TxnPartyRole;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "txn_parties"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "TxnParty",
    export_to = "../../../packages/types/src/db/TxnParty.ts"
)]
pub struct Model {
    pub id: String,
    pub transaction_id: String,
    pub user_id: Option<String>,
    pub contact_id: Option<String>,
    pub role: TxnPartyRole,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    TransactionId,
    UserId,
    ContactId,
    Role,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Transactions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id | Self::UserId | Self::ContactId => {
                ColumnType::String(StringLen::None).def().null()
            }
            Self::TransactionId | Self::Role => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Transactions => Entity::belongs_to(super::transactions::Entity)
                .from(Column::TransactionId)
                .to(super::transactions::Column::Id)
                .into(),
        }
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
