//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::enums::GroupRole;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &'static str {
        "users"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, TS,
)]
#[ts(
    export,
    rename = "User",
    export_to = "../../../packages/types/src/db/User.ts"
)]
pub struct Model {
    pub id: String,
    pub name: String,
    pub email: String,
    pub email_verified: bool,
    pub image: Option<String>,
    pub phone: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub username: Option<String>,
    pub display_username: Option<String>,
    pub role: Option<GroupRole>,
    pub banned: Option<bool>,
    pub ban_reason: Option<String>,
    pub ban_expires: Option<DateTimeWithTimeZone>,
    pub two_factor_enabled: Option<bool>,
    pub phone_number: Option<String>,
    pub phone_number_verified: Option<bool>,
    #[ts(as = "Option<crate::ExportedJsonValue>")]
    pub metadata: Option<Json>,
    pub associated_contact_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Email,
    EmailVerified,
    Image,
    Phone,
    IsActive,
    CreatedAt,
    UpdatedAt,
    Username,
    DisplayUsername,
    Role,
    Banned,
    BanReason,
    BanExpires,
    TwoFactorEnabled,
    PhoneNumber,
    PhoneNumberVerified,
    Metadata,
    AssociatedContactId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Accounts,
    Budgets,
    Categories,
    ContactLinks,
    LedgerTabs,
    P2pRequests,
    Sessions,
    Subscriptions,
    Transactions,
    UserGroups,
    UserUpiIds,
    Wallets,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id
            | Self::Image
            | Self::Phone
            | Self::Username
            | Self::DisplayUsername
            | Self::Role
            | Self::BanReason
            | Self::PhoneNumber
            | Self::AssociatedContactId => ColumnType::String(StringLen::None).def().null(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Email => ColumnType::String(StringLen::None).def().unique(),
            Self::EmailVerified | Self::IsActive => ColumnType::Boolean.def(),
            Self::CreatedAt | Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::Banned | Self::TwoFactorEnabled | Self::PhoneNumberVerified => {
                ColumnType::Boolean.def().null()
            }
            Self::BanExpires => ColumnType::TimestampWithTimeZone.def().null(),
            Self::Metadata => ColumnType::Json.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Accounts => Entity::has_many(super::accounts::Entity).into(),
            Self::Budgets => Entity::has_many(super::budgets::Entity).into(),
            Self::Categories => Entity::has_many(super::categories::Entity).into(),
            Self::ContactLinks => Entity::has_many(super::contact_links::Entity).into(),
            Self::LedgerTabs => Entity::has_many(super::ledger_tabs::Entity).into(),
            Self::P2pRequests => Entity::has_many(super::p2p_requests::Entity).into(),
            Self::Sessions => Entity::has_many(super::sessions::Entity).into(),
            Self::Subscriptions => Entity::has_many(super::subscriptions::Entity).into(),
            Self::Transactions => Entity::has_many(super::transactions::Entity).into(),
            Self::UserGroups => Entity::has_many(super::user_groups::Entity).into(),
            Self::UserUpiIds => Entity::has_many(super::user_upi_ids::Entity).into(),
            Self::Wallets => Entity::has_many(super::wallets::Entity).into(),
        }
    }
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::budgets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Budgets.def()
    }
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::contact_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactLinks.def()
    }
}

impl Related<super::ledger_tabs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerTabs.def()
    }
}

impl Related<super::p2p_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::P2pRequests.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGroups.def()
    }
}

impl Related<super::user_upi_ids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserUpiIds.def()
    }
}

impl Related<super::wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallets.def()
    }
}

impl Related<super::contacts::Entity> for Entity {
    fn to() -> RelationDef {
        super::contact_links::Relation::Contacts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::contact_links::Relation::Users.def().rev())
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_groups::Relation::Groups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_groups::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
