// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";

export type BankTransaction = { transaction_date: string, description: string, mode: string | null, debit_amount: string | null, credit_amount: string | null, balance: string | null, contact_name: string | null, upi_id: string | null, reference_number: string | null, category_id: string | null, wallet_id: string | null, contact_id: string | null, metadata: JsonValue | null, };
