// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankTransaction } from "./BankTransaction";

export type BankStatementResponse = { transactions: Array<BankTransaction>, bank_name: string, account_number: string | null, statement_period: string, };
