// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankStatementResponse } from "./BankStatementResponse";

export type BankExtractionResult = { raw_text: string, doc_type: string, confidence_score: number, bank_data: BankStatementResponse, };
