// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessedOcr } from "./ProcessedOcr";

export type ConfirmOcrRequest = { manual_data?: ProcessedOcr, };
