// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Contact = { id: string, name: string, phone: string | null, is_pinned: boolean, normalized_name: string | null, phonetic_name: string | null, };
