// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetPeriod } from "./BudgetPeriod";

export type CreateBudgetRequest = { category_id?: string, amount: string, period: BudgetPeriod, };
