// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionDirection } from "./TransactionDirection";

export type CreateManualTransactionRequest = { amount: string, date: string, purpose_tag: string, category_id?: string, direction: TransactionDirection, source_wallet_id?: string, destination_wallet_id?: string, contact_id?: string, notes?: string, };
