// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WalletType } from "./WalletType";

export type CreateWalletRequest = { name: string, type: WalletType, initial_balance: string, };
