// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FullTxn = { amount: string, direction: string, date: string, status: string | null, category_id: string | null, contact_name: string | null, purpose_tag: string | null, };
