// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";

export type OcrJob = { id: string, user_id: string, status: string, r2_key: string, processed_data: JsonValue | null, error: string | null, created_at: string, updated_at: string, p_hash: string | null, auto_confirm: boolean, wallet_id: string | null, category_id: string | null, transaction_id: string | null, started_at: string | null, retry_count: number, last_error: string | null, scheduled_at: string | null, raw_key: string | null, is_high_res: boolean, schema_version: number, resolution_candidates: JsonValue | null, trace_id: string | null, batch_id: string | null, idempotency_key: string | null, };
