// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transaction } from "./Transaction";

/**
 * Response for OCR transaction creation.
 */
export type OcrTransactionResponse = { transaction: Transaction, contact_created: boolean, batch_count: number, };
