// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";
import type { P2pRequestStatus } from "./P2pRequestStatus";

export type P2pRequest = { id: string, sender_user_id: string, receiver_email: string, transaction_data: JsonValue, status: P2pRequestStatus, linked_txn_id: string | null, };
