// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type P2pRequestStatus = "PENDING" | "MAPPED" | "REJECTED" | "APPROVED" | "GROUP_INVITE";
