// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";
import type { P2pRequestStatus } from "./P2pRequestStatus";

/**
 * P2P request with sender's name.
 */
export type P2pRequestWithSender = { sender_name: string | null, id: string, sender_user_id: string, receiver_email: string, transaction_data: JsonValue, status: P2pRequestStatus, linked_txn_id: string | null, };
