// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionWithDetail } from "./TransactionWithDetail";

/**
 * Paginated response for transactions.
 */
export type PaginatedTransactions = { items: Array<TransactionWithDetail>, total_count: number, };
