// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessImageOcrRequest = { key: string, raw_key?: string, p_hash?: string, auto_confirm?: boolean, wallet_id?: string, category_id?: string, batch_id?: string, };
