// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitDetail } from "./SplitDetail";

export type SplitTransactionRequest = { transaction_id: string, splits: Array<SplitDetail>, };
