// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatementRowMinimal = { id: string, date: string, description: string, debit: string | null, credit: string | null, };
