// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransactionMinimal = { id: string, date: string, amount: string, notes: string | null, purpose_tag: string | null, };
