// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankExtractionResult } from "./BankExtractionResult";
import type { GPayExtraction } from "./GPayExtraction";
import type { OcrResult } from "./OcrResult";

export type TypedProcessedOcr = { "doc_type": "GPAY", data: GPayExtraction, r2_key: string | null, } | { "doc_type": "BANK_STATEMENT", data: BankExtractionResult, r2_key: string | null, } | { "doc_type": "GENERIC", data: OcrResult, r2_key: string | null, };
