// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionStatus } from "./TransactionStatus";

export type UpdateTransactionRequest = { amount?: string | null, date?: string, purpose_tag?: string, category_id?: string, status?: TransactionStatus, notes?: string, source_wallet_id?: string, destination_wallet_id?: string, contact_id?: string, };
