// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WalletType } from "./WalletType";

export type Wallet = { id: string, user_id: string, name: string, type: WalletType, balance: string, bank_name: string | null, account_number: string | null, created_at: string, updated_at: string, };
